# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'des.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 500)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("cryptography.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-color: rgb(255, 255, 255);")
        self.text = QtWidgets.QLineEdit(Form)
        self.text.setGeometry(QtCore.QRect(197, 110, 330, 40))
        self.text.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 87 18pt \"Arial Black\";\n"
"")
        self.text.setText("")
        self.text.setObjectName("text")
        self.resultat = QtWidgets.QLineEdit(Form)
        self.resultat.setGeometry(QtCore.QRect(192, 424, 330, 40))
        self.resultat.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 87 18pt \"Arial Black\";")
        self.resultat.setReadOnly(True)
        self.resultat.setObjectName("resultat")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(238, 20, 251, 61))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"text-decoration: underline;\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"font: 87 22pt \"Arial Black\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(710, 460, 81, 31))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_4.setObjectName("label_4")
        self.cle = QtWidgets.QLineEdit(Form)
        self.cle.setGeometry(QtCore.QRect(197, 228, 330, 40))
        self.cle.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 87 18pt \"Arial Black\";\n"
"")
        self.cle.setText("")
        self.cle.setObjectName("cle")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(550, 250, 231, 201))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("cryptography.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 111, 101))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("file.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(40, 190, 111, 101))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("digital-key.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(180, 300, 331, 81))
        self.pushButton.setStyleSheet("font: 75 34pt \"Arial Narrow\";\n"
"color: rgb(255, 255, 255);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("key.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(80, 80))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "DES Cryptage"))
        self.label_3.setText(_translate("Form", "DES : Cryptage"))
        self.label_4.setText(_translate("Form", "Groupe 1 "))
        self.pushButton.setText(_translate("Form", "Cryptage"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
